name: football_analysis_system
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.3
  - cudnn=8.2.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pip:
    - ultralytics==8.2.63
    - opencv-python==4.10.0.84
    - roboflow==1.1.36
    - supervision==0.22.0
    - pandas==2.2.2
    - numpy==1.23.5
    - matplotlib==3.9.1
    - scikit-learn==1.5.1
